name: Build WLED (UI-skin)

on:
  push:
    branches: [ main, ui-skin ]
    tags: [ "v*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    # Pick the envs you actually use (see platformio.ini)
      matrix:
        env: [ esp32dev ] # add more: esp32c3dev, esp32s3dev, esp8266_1m, etc.

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: |
            ~/.platformio
            .pio
          key: pio-${{ runner.os }}-${{ hashFiles('**/platformio.ini') }}
          restore-keys: |
            pio-${{ runner.os }}-

      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Only needed if you edited files in wled00/data (which you did)
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build UI assets
        run: |
          npm ci
          npm run build

      - name: Build firmware (${{ matrix.env }})
        run: pio run -e ${{ matrix.env }}

      - name: Upload artifact (firmware.bin)
        uses: actions/upload-artifact@v4
        with:
          name: wled-${{ matrix.env }}-${{ github.ref_name }}
          path: .pio/build/${{ matrix.env }}/firmware.bin
          if-no-files-found: error

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/firmware.bin
